### ISSUE TITLE
Normalise responses across server

### ISSUE THREAD

**Issue by sysr-q** [bloocoin/bloocoin-server#5]
Currently the server varies responses. Sometimes it's JSON, sometimes it's a string, sometimes it's an integer.
This is no good, it should be the same for everything, with modified payloads.

So I propose a new reply structure like this:

``` python
{
    "success": bool,
    "message": None, # incase of errors,
    "payload": { # What the command returns (None if errors)
        "this": "that",
        "foo": "bar"
    }
}
```

This could also be further enhanced by making a command base class that commands are subclassed from, which allows simple `self.error('something went wrong, lel')` and `self.success({"this": "that"})` methods, to really clean it all up.

@Max00355 - this is what I was talking about earlier.

**Comment by sysr-q** [comment]
I'm working on this in the `json-responses` branch, which you can see [here](https://github.com/bloocoin/bloocoin-server/tree/json-responses).
This will be a fairly large update, so backwards compatibility will more than likely be non-existent, unless I write special backwards compat. code, which I'm not sure is worth it. Just better for everyone to update.

**Comment by f-prime** [comment]
Damn, the clients will have to be completely rewritten almost...

**Comment by sysr-q** [comment]
Well, yes, but it makes it much better in terms of protocol. It'll be a lot more standardized across it all, rather than some being JSON, some being strings, and ending up with decoding errors and whatnot.

**Comment by f-prime** [comment]
I suppose you are right, we might as well just recreate the whole thing though... maybe go for a p2p approach this time?

**Comment by sysr-q** [comment]
I'm not sure how you'd go with a P2P thing, so if you want to, try and figure it out, sure.
ATM, this just cleans it up, so whilst it's still the same system, it's just easier for developers to make clients and tools.

I've never really done any work with P2P, so I have no idea how it works.

**Comment by f-prime** [comment]
I had an idea as to how the P2P system could work, obvoiusly we will need some type of central server otherwise the clients would never be able to find eachother. I was thinking of either using IRC or HTTP for the clients to exchange information and find eachother if that makes sense. We can talk more about this on IRC.

**Comment by sysr-q** [comment]
Well this is done as of #6 being merged, so everything is OK.
